### PR TITLE
Publish to PyPI via Trusted Publisher

### PR DESCRIPTION
**Pull request by amureki**
https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect

### CODE REVIEW

**Comment by codingjoe** [comment]
The release failed.

**Comment by amureki** [comment]
@codingjoe I know, I don't have access to PyPI to update the config there. Already sent you an email about it once it failed.

**Comment by codingjoe** [comment]
I will set it up.

**Comment by codingjoe** [comment]
OK, done and uploaded.

**Comment by amureki** [comment]
Thank you!

**Pull request merged**
